application:
    domain: back.boe.dev

databases:
    auth:
        host: '127.0.0.1'
        user: 'root'
        password: 'pw4benoit'
        database: 'boe'
        pool_size: 10

crud:
    list_limit: 5000

cache:
    'cache.type': 'memory'

flask:
    debug: False
    profiling: False