application:
    domain: back.boe.dev

databases:
    auth:
        host: localhost
        user: 'back_boe'
        password: 'back_pass'
        database: 'boe'
        pool_size: 10

crud:
    list_limit: 5000

cache:
    'cache.type': 'memory'

flask:
    debug: False
    profiling: False
